---
- name: Installing dependencies
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Removing Docker if avalable.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-ce
    - docker-engine

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: yes

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes


- name: Install Docker.
  package:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - docker-ce

  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes
